quiz/models.py
from quiz import db
from flask_login import UserMixin


class User(UserMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)  # primary keys are required by SQLAlchemy
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    total = db.Column(db.Integer)
    scores = db.relationship("Score", backref="user", lazy="dynamic")

    is_admin = db.Column(db.Boolean, default=False)

    def get(self, username):
        return self.id


class Score(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(20), index=True, nullable=True)
    question = db.Column(db.String(20), index=True, nullable=True)
    level = db.Column(db.String(20), index=True, nullable=True)
    score = db.Column(db.Integer, index=True, nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __init__(self, category, question, level, score, user_id):
        self.category = category
        self.question = question
        self.level = level
        self.score = score
        self.user_id = user_id

quiz/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import Config
from flask_migrate import Migrate

db = SQLAlchemy()


def create_app():

    app = Flask(__name__)
    migrate = Migrate(app, db)

    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///quiz.db"
    app.config.from_object(Config)

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = "main.login"
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        # since the user_id is just the primary key of our user table, use it in the query for the user
        return User.query.get(int(user_id))

    # blueprint for routes routes in our app
    from .routes import main as main_blueprint

    app.register_blueprint(main_blueprint)

    # blueprint for non-routes parts of app
    from .main import base as base_blueprint

    app.register_blueprint(base_blueprint)

    return app

quiz/main.py
from flask import Blueprint, render_template, redirect, request, session
from flask_login import login_required, current_user
from quiz.client import get_me_question
from quiz import db
from quiz.models import User, Score
from quiz.utilities import check_answers, total_score

base = Blueprint("base", __name__)


@base.route("/")
def index():
    users = User.query.all()

    return render_template("index.html", users=users)


@base.route("/admin/")
@login_required
def admin_index():
    users = User.query.all()

    return render_template("admin_index.html", users=users)


@base.route("/admin/delete/<username>")
@login_required
def terminator(username):

    user = User.query.filter_by(username=username).first()

    db.session.delete(user)
    db.session.commit()

    return redirect("admin_index.html")


@base.route("/profile/", methods=["GET"])
@login_required
def profile():
    username = current_user.username
    user = User.query.filter_by(username=username).first()
    scores = Score.query.filter_by(user_id=user.id).all()
    total = total_score(user, scores)

    return render_template("profile.html", username=username, scores=scores, total=total)


@base.route("/trivia/", methods=["GET"])
@login_required
def trivia():
    question = get_me_question()
    session["q"] = question
    return render_template("trivia.html", username=current_user.username, question=question)


@base.route("/trivia/check/", methods=["POST"])
@login_required
def correct():
    username = current_user.username
    user = User.query.filter_by(username=username).first()

    quest = session.get("q", None)

    if request.form["my_answer"] == quest["correct_answer"]:
        answers = request.form["my_answer"]
        check_answers(answers, quest, user)
    else:
        answers = request.form["my_answer"]
        check_answers(answers, quest, user)
    return redirect("/trivia/")

quiz/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from flask_login import login_user, logout_user, login_required
from . import db

main = Blueprint("main", __name__)


@main.route("/login/", methods=["GET"])
def login():
    return render_template("login.html")


@main.route("/signup/")
def signup():
    return render_template("signup.html")


@main.route("/login/", methods=["POST"])
def login_post():
    username = request.form.get("username")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = User.query.filter_by(username=username).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash("Please check your login details and try again.")
        return redirect(
            url_for("main.login")
        )  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for("base.profile"))


@main.route("/signup/", methods=["POST"])
def signup_post():
    username = request.form.get("username")
    password = request.form.get("password")

    user = User.query.filter_by(
        username=username
    ).first()  # if this returns a user, then the username already exists in database

    if (
        user
    ):  # if a user is found, we want to redirect back to signup page so user can try again
        flash("Username already exists")
        return redirect(url_for("main.login"))

    # check if all data given
    if not request.form["username"] or not request.form["password"]:
        flash("Please enter all required data", "error")
        return redirect(url_for("main.signup"))
    else:
        # create a new user with the form data. Hash the password so the plaintext version isn't saved.
        new_user = User(
            username=username,
            password=generate_password_hash(password, method="sha256"),
        )

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("main.login"))


@main.route("/logout/")
@login_required
def logout():
    logout_user()
    return redirect(url_for("base.index"))

quiz/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>
{% block head %} {% endblock %}

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('base.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_admin %}
                            <a href="{{ url_for('base.admin_index') }}" class="navbar-item">
                                Admin Index
                                {% endif %}
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('base.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('base.trivia') }}" class="navbar-item">
                                Trivia
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('main.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('main.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

quiz/templates/index.html
{% extends "base.html" %}
{% block head %}
<style>
    .score_board {
        text-align: -webkit-center;
        
    }

    .hero.is-fullheight .hero-body {
        align-items: baseline;
        text-align: -webkit-center;
    }
    
    table,
    td {
        border: 1px solid #333;
        text-align:center;
    }

    thead,
    tfoot {
        background-color: #333;
        color: #fff;
    }

</style>
<title>Quiz App | Score Board</title>
{% endblock %}
{% block content %}
<div class="ht"><br>
    <h1 class="title">
        Welcome to My Quiz
    </h1>
    <h2 class="subtitle"><br>
        Based on Open Trivia Database
    </h2>
</div>
<br><br>

<div class="score_board">
    <table>
        <thead>
            <tr>
                <th colspan="2" style="color:#fff; text-align: -webkit-center;">Score Board</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td> Username </td>
                <td> Total Score </td>
            </tr>
            
            {% for user in users %}
            <tr>
                <td style="text-align:center;"> {{ user.username }} </td>
                <td style="text-align:center;"> {{ user.total }} </td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>

</div>

{% endblock %}

quiz/templates/login.html
{% extends "base.html" %}
{% block head %} <title>Quiz App | Login Page</title> {% endblock %}
{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login/">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" id="username" placeholder="Your Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" id="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth" id="L0g">Login</button>
        </form>
    </div>
</div>
{% endblock %}

quiz/templates/profile.html
{% extends "base.html" %}
{% block head %} <title>Quiz App | Profile Page</title>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd00;
    }
</style>
{% endblock %}

{% block content %}
<h1 style="font-size: 25px;">
    Welcome {{ username }}!
</h1><br>
Yours current total is : {{ total }} <br><br>
<h2>Yours Score Board</h2><br>
<div class="score_board">
    <table>
        <tr>
            <th>Quiz Category</th>
            <th>Quiz Question</th>
            <th>Difficulty level</th>
            <th>Score</th>
        </tr>
        {% for score in scores %}
        <tr>
            <td>{{ score.category }}</td>
            <td>{{ score.question }}</td>
            <td>{{ score.level}}</td>
            <td>{{ score.score}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

quiz/templates/signup.html
{% extends "base.html" %}
{% block head %} <title>Quiz App | Sign Up Page</title> {% endblock %}
{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('main.login') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup/">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" id="username_signup" placeholder="Username" autofocus="">
                </div>
            </div>

            AS <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" id="password_signup" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth" id="sign_button">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

quiz/templates/trivia.html
{% extends "base.html" %}
{% block head %} <title>Quiz App | Trivia</title> {% endblock %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul class=flashes>
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

{% block content %}
<h1 style="font-size: 22px;">
    Welcome to your Trivia Game {{ username }}!
</h1>
<div class="q&a">
    <form action="/trivia/" method="GET">
        <h11> Question from: </h11>
        <p name="category" id="category"> {{ question.category }} - category</p>
        <p name="difficulty" id="difficulty">Difficulty: {{ question.difficulty }}</p>
        <p>There is yours question</p>
        <p name="question" id="question">{{ question.question }} </p>
    </form>
    <form action="/trivia/check/" method="POST">
        <button name="my_answer" value="True">True</button>
        <button name="my_answer" value="False">False</button>
    </form>
</div>
{% endblock %}